Repository Seafety/SofttekPreviewFront, pull requests merged in 2024-08, with the labels that each got.

#1 Adicionando as rotas no projeto
  package.json
  src/App.css
  src/App.jsx
  src/Pages/Home/Forecast/index.jsx
  src/Pages/Home/Tendencia/index.jsx
  src/Pages/Home/index.jsx
  src/Routes.jsx
  src/index.css
  src/main.jsx
  yarn.lock
Labels: IN QA

#7 Adicionando o componente de status
  src/Components/Atoms/Status/index.jsx
  src/Components/Atoms/Status/index.module.scss
  src/Components/Templates/HomeTemplate/index.jsx
  src/Styles/_variables.scss
Labels: IN QA

#10 fix: :bug: fixing the / bug when navigated by the url
  src/Components/Organisms/SubNavDash/index.jsx
Labels: IN QA

#11 feat: :heavy_plus_sign: add chart.js and react-chartjs-2
  package.json
  src/Components/Atoms/InfoBoxView/index.jsx
  src/Components/Atoms/InfoBoxView/index.module.scss
  src/Components/Molecules/RevenueCostChart/index.jsx
  src/Components/Organisms/FinanceVision/index.jsx
  src/Components/Organisms/FinanceVision/index.module.scss
  src/Components/Organisms/SubNavDash/index.module.scss
  src/Pages/Home/RealTime/index.jsx
  yarn.lock
Labels: IN QA

#13 feat: ✨ add demandas page
  src/Components/Organisms/Header/Index.jsx
  src/Components/Organisms/SubNavDash/index.jsx
  src/Components/Templates/DemandasTemplate/index.jsx
  src/Pages/Demandas/Board/index.jsx
  src/Pages/Demandas/Data/index.jsx
  src/Pages/Demandas/index.jsx
  src/Routes.jsx
Labels: IN PROGRESS

#21 Página de Demandas/Data
  src/Components/Templates/DashSectionTemplate/index.module.scss
Labels: IN QA

#19 Adicionando section de análise de projetos
  src/Assets/alert-green.svg
  src/Assets/alert-orange.svg
  src/Assets/alert-red.svg
  src/Components/Atoms/InfoBoxView/index.module.scss
  src/Components/Organisms/ContractsSection/index.jsx
  src/Components/Organisms/ContractsSection/index.module.scss
  src/Components/Templates/DashSectionTemplate/index.module.scss
Labels: IN QA

#24 Eiji create design dashboard
  package.json
  src/Components/Atoms/Status/index.jsx
  src/Components/Molecules/Area/index.jsx
  src/Components/Molecules/Area/index.module.scss
  src/Components/Molecules/RevenueCostChart/index.jsx
  src/Components/Organisms/ComplexChart/index.jsx
  src/Components/Organisms/Header/index.module.scss
  src/Components/Organisms/StatusArea/index.jsx
  src/Components/Organisms/StatusArea/index.module.scss
  src/Components/Organisms/SubNavDash/index.module.scss
  src/Components/Templates/DashSectionTemplate/index.module.scss
  src/Pages/Demandas/Data/index.jsx
  src/Pages/Home/RealTime/index.jsx
  src/Pages/Home/RealTime/index.module.scss
  src/Styles/_global.scss
  yarn.lock
Labels: IN QA, IN PROGRESS

#25 adding responsiveness
  src/Components/Atoms/InfoBoxView/index.module.scss
  src/Components/Molecules/Area/index.jsx
  src/Components/Molecules/Area/index.module.scss
  src/Components/Organisms/FinanceSection/index.module.scss
  src/Components/Organisms/Header/index.module.scss
  src/Components/Organisms/StatusArea/index.module.scss
  src/Components/Templates/DashSectionTemplate/index.module.scss
  src/Pages/Home/RealTime/index.module.scss
Labels: IN QA, IN PROGRESS

#26 Eiji fix demands page
  src/Components/Molecules/CriticidadeBar/index.jsx
  src/Components/Molecules/Table/index.jsx
  src/Components/Molecules/Table/index.module.scss
  src/Components/Organisms/ChamadosConsultorSection/index.jsx
  src/Components/Organisms/ConclusionChart/index.jsx
  src/Components/Organisms/ConsultoresDisponiveisSection/index.jsx
  src/Components/Organisms/OpenTickets/index.jsx
  src/Components/Organisms/Table/index.module.scss
  src/Components/Templates/DemandasTemplate/index.module.scss
  src/Pages/Demandas/Data/index.jsx
Labels: IN QA
